// <auto-generated />
using System;
using ICMarkets.DeveloperTest.Datacontext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ICMarkets.DeveloperTest.API.Migrations
{
    [DbContext(typeof(ICMarketsDbContext))]
    [Migration("20230911081107_Alter-Table-BlockchainData-Added_Columns")]
    partial class AlterTableBlockchainDataAdded_Columns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.18");

            modelBuilder.Entity("ICMarkets.DeveloperTest.Datacontext.Entities.BlockchainDataEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("BaseFee")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_fee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<long>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<long>("HighFeePerKb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("high_fee_per_kb");

                    b.Property<long>("HighGasPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("high_gas_price");

                    b.Property<long>("HighPriorityFee")
                        .HasColumnType("INTEGER")
                        .HasColumnName("high_priority_fee");

                    b.Property<string>("LastForkHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_fork_hash");

                    b.Property<long>("LastForkHeight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("last_fork_height");

                    b.Property<string>("LatestUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("latest_url");

                    b.Property<long>("LowFeePerKb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("low_fee_per_kb");

                    b.Property<long>("LowGasPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("low_gas_price");

                    b.Property<long>("LowPriorityFee")
                        .HasColumnType("INTEGER")
                        .HasColumnName("low_priority_fee");

                    b.Property<long>("MediumFeePerKb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medium_fee_per_kb");

                    b.Property<long>("MediumGasPrice")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medium_gas_price");

                    b.Property<long>("MediumPriorityFee")
                        .HasColumnType("INTEGER")
                        .HasColumnName("medium_priority_fee");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PeerCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("peer_count");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_hash");

                    b.Property<string>("PreviousUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("previous_url");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<int>("UnconfirmedCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("unconfirmed_count");

                    b.HasKey("Id")
                        .HasName("pk_blockchain_data");

                    b.ToTable("blockchain_data", (string)null);
                });

            modelBuilder.Entity("ICMarkets.DeveloperTest.Datacontext.Entities.ExceptionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("exception_message");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("request_id");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stack_trace");

                    b.HasKey("Id")
                        .HasName("pk_exceptions_audit");

                    b.ToTable("exceptions_audit", (string)null);
                });

            modelBuilder.Entity("ICMarkets.DeveloperTest.Datacontext.Entities.RequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.HasKey("Id")
                        .HasName("pk_requests_audit");

                    b.ToTable("requests_audit", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
